[package]
name = "ktcplist"
version = "0.1.9999"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
libc = { path = "/usr/home/kostik/work/langs/rust/libc" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }